(function(g){var window=this;var m4=function(a){var b={format:a.o,languageCode:a.l,languageName:a.C,displayName:g.eI(a),kind:a.A,name:a.B,id:a.ia,is_servable:a.L,is_translateable:a.F,vss_id:a.D};a.g&&(a=a.g,b.translationLanguage={languageCode:a.languageCode,languageName:a.languageName,languageOriginal:a.g,id:a.id,is_default:a.isDefault});return b},n4=function(a){return a.g?a.g.languageCode:a.l},vya=function(a,b){var c=new g.dI;
c.l=a.l;c.C=a.C;c.B=a.B;c.A=a.A;c.F=a.F;c.D=a.D;c.H=a.H;c.g=b;return c},wya=function(a){a=g.kd(window.document,"track",void 0,a.g);
for(var b=0;b<a.length;b++)g.Dd(a[b])},xya=function(a,b){for(var c in a)if(!(c in b)||a[c]!==b[c])return!1;
for(c in b)if(!(c in a))return!1;return!0},o4=function(a){if(!yya.test(a))throw Error("'"+a+"' is not a valid hex color");
4==a.length&&(a=a.replace(zya,"#$1$1$2$2$3$3"));a=a.toLowerCase();return[(0,window.parseInt)(a.substr(1,2),16),(0,window.parseInt)(a.substr(3,2),16),(0,window.parseInt)(a.substr(5,2),16)]},p4=function(a,b,c,d,e,f,k){f=void 0===f?!1:f;
k=void 0===k?null:k;g.dQ.call(this,a,a+b,{priority:c,namespace:"captions"});this.windowId=d;this.text=e;this.C=f;this.l=k},q4=function(a,b,c,d,e){g.dQ.call(this,a,a+b,{priority:c,
namespace:"captions"});this.id=d;this.params=e;this.l=[]},s4=function(a){a=void 0===a?{}:a;
var b="_"+r4++;return new q4(0,0x8000000000000,0,b,a)},t4=function(a,b,c,d,e,f){var k={};
g.Ea(k,b);g.Ea(k,a.params);g.Ea(k,c);var l={};g.Ea(l,b.jb);a.params.jb&&g.Ea(l,a.params.jb);g.Ea(l,c.jb);k.jb=l;g.V.call(this,{G:"div",M:"caption-window",T:{id:"caption-window-"+a.id,dir:1==k.dk?"rtl":"ltr",tabindex:"0","aria-live":"assertive",lang:k.lang},J:[{G:"span",M:"captions-text"}]});this.o=[];this.I=!1;this.D=a;this.C=[];this.F=[];this.ra=e;this.oa=f;this.B=null;this.W=.96*e;this.da=.96*f;this.l=k;this.na=c;this.A=this.wa["captions-text"];this.fa=null!=this.A.style["box-decoration-break"]||
null!=this.A.style["-webkit-box-decoration-break"];this.K=d/360*16;this.type=0;this.Y=this.K*Aya(l);a=new g.EF(this.element,!0);g.M(this,a);a.subscribe("dragstart",this.UM,this);a.subscribe("dragmove",this.TM,this);a.subscribe("dragend",this.SM,this);this.ca=this.ba=0;a="";this.l.pk&&(a=o4(this.l.windowColor),a="rgba("+a[0]+","+a[1]+","+a[2]+","+this.l.pk+")");b={"background-color":a,display:!1===this.l.isVisible?"none":"","text-align":Bya[this.l.textAlign]};this.fa&&(b["border-radius"]=a?this.Y/
8+"px":"");g.nh(this.element,b);switch(this.l.Wg){case 0:case 1:case 2:g.S(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.S(this.element,"ytp-caption-window-bottom")}},Aya=function(a){var b=1+.25*(a.gj||0);
if(0==a.offset||2==a.offset)b*=.8;return b},u4=function(a,b){var c={},d=b.background?b.background:a.l.jb.background;
if(null!=b.Ze||b.background){var e=null!=b.Ze?b.Ze:a.l.jb.Ze;d=o4(d);c.background="rgba("+d[0]+","+d[1]+","+d[2]+","+e+")";a.fa&&(c["box-decoration-break"]="clone",c["border-radius"]=a.Y/8+"px")}if(null!=b.gj||null!=b.offset)c["font-size"]=a.K*Aya(b)+"px";d=1;e=b.color||a.l.jb.color;if(b.color||null!=b.Gh)e=o4(e),d=null==b.Gh?a.l.jb.Gh:b.Gh,e="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")",c.color=e,c.fill=e;var f=b.Uh;0==f&&(f=null);if(f){e="rgba(34, 34, 34, "+d+")";var k="rgba(204, 204, 204, "+d+")";b.Fw&&
(k=e=b.Fw);var l=a.K/16/2,m=Math.max(l,1),n=Math.max(2*l,1),q=Math.max(3*l,1),r=Math.max(5*l,1);d=[];switch(f){case 4:for(;q<=r;q+=l)d.push(n+"px "+n+"px "+q+"px "+e);break;case 1:n=2<=window.devicePixelRatio?.5:1;for(f=m;f<=q;f+=n)d.push(f+"px "+f+"px "+e);break;case 2:d.push(m+"px "+m+"px "+k);d.push("-"+m+"px -"+m+"px "+e);break;case 3:for(q=0;5>q;q++)d.push("0 0 "+n+"px "+e)}c["text-shadow"]=d.join(", ")}e="";switch(b.fontFamily){case 1:e='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';
break;case 2:e='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:e='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:e='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:e='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:e=g.rE()?'"Carrois Gothic SC", sans-serif-smallcaps':'"Arial Unicode Ms", Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:e=
'"YouTube Noto", Roboto, "Arial Unicode Ms", Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}e&&(c["font-family"]=e);e=b.offset;null==e&&(e=a.l.jb.offset);switch(e){case 0:c["vertical-align"]="sub";break;case 2:c["vertical-align"]="super"}7==b.fontFamily&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.As&&(c["font-style"]="italic");b.underline&&(c["text-decoration"]="underline");b.Jr&&(c.visibility="hidden");return c},Cya=function(a,b,c){a.I=a.I||!!c;
var d={};g.Ea(d,a.l.jb);g.Ea(d,c||b.l);g.Ea(d,a.na.jb);c=a.C[0];if(c&&d.background==c.background&&d.Ze==c.Ze&&!!d.Jr==!!c.Jr&&d.Uh==c.Uh){var e;for(e=0;e<a.C.length;e++)if(xya(d,a.C[e])){var f=a.F[e];break}if(!f){e={};for(var k in d)d[k]!=c[k]&&(e[k]=d[k]);f=g.xd("SPAN");g.nh(f,u4(a,e));a.F[0].appendChild(f);e=1}a.F.length=e;a.C.length=e}else a.F.length=0,a.C.length=0,f=g.xd("SPAN"),g.nh(f,u4(a,d)),a.A.appendChild(f);a.B&&a.B.parentNode!=f&&(g.Dd(a.B),f.appendChild(a.B));c=(k=g.v(b.text))?b.text.split("\n"):
[b.text];for(e=0;e<c.length;e++){var l=c[e];if(0<e||0==a.o.length||!b.C){if(0<e||0!=a.o.length){var m=g.xd("BR");f.appendChild(m)}f.appendChild(g.yd("\u00a0"));a.B=g.yd("\u00a0");f.appendChild(a.B)}l&&(m=a.B,m.parentNode&&m.parentNode.insertBefore(k?g.yd(l):l,m))}a.C.push(d);a.F.push(f);a.o.push(b)},Dya=function(){},w4=function(){this.A=this.l=this.mode=this.o=0;
this.B=new v4(this);this.C=new v4(this);this.g=[];this.clear()},Fya=function(a,b,c){if(255==a&&255==b||!a&&!b)return{Qm:a,
Rm:b,result:0};a=Eya[a];b=Eya[b];if(a&128){if(!(b&128)&&0!=c.g&&c.l==b)return{Qm:a,Rm:b,result:1}}else if(b&128&&1<=a&&31>=a)return{Qm:a,Rm:b,result:2};return{Qm:a,Rm:b,result:3}},Hya=function(a,b,c,d){255==b&&255==c||!b&&!c?(45==++a.A&&a.reset(),a.B.g.clear(),a.C.g.clear()):(a.A=0,Gya(a.B,b,c,d))},Iya=function(a,b){a.g.sort(function(a,b){var c=a.time-b.time;
return 0==c?a.order-b.order:c});
for(var c=0;c<a.g.length;c++){var d=a.g[c];a.l=d.time;0==d.type?Hya(a,d.Aw,d.Bw,b):1==d.type&&a.o&496&&Gya(a.C,d.Aw,d.Bw,b)}a.g.length=0},x4=function(){this.g=0},y4=function(){this.l=this.o=this.g=0},z4=function(){this.timestamp=this.ue=0},A4=function(a){this.o=[];
for(var b=0;15>=b;b++){this.o[b]=[];for(var c=0;32>=c;c++)this.o[b][c]=new z4}this.g=this.l=this.Ic=0;this.style=new x4;this.B=a;this.A=0},B4=function(a,b){if(3==a.style.g){for(var c=0,d=0,e=a.B.l+0,f="",k="",l=e,m=1;15>=m;++m){for(var n=!1,q=d?d:1;32>=q;++q){var r=a.o[m][q];
if(0!=r.ue){0==c&&(c=m,d=q);n=String.fromCharCode(r.ue);var u=r.timestamp;u<e&&(e=u);r.timestamp=l;k&&(f+=k,k="");f+=n;n=!0}if((0==r.ue||32==q)&&n){k="\n";break}else if(d&&!n)break}if(c&&!n)break}f&&b.A(c,d,e,l,f)}else for(d=c=0,f=e=a.B.l+0,k=1;15>=k;++k)for(l="",m=1;32>=m;++m)if(q=a.o[k][m],r=q.ue,0!=r&&(0==c&&(c=k,d=m),n=String.fromCharCode(r),u=q.timestamp,u<=e&&(e=u),l+=n,q.reset()),32==m||0==r)l&&b.A(c,d,e,f,l),e=f,l="",d=c=0},Nya=function(a,b){switch(a){case 0:return Jya[(b&127)-32];
case 1:return Kya[b&15];case 2:return Lya[b&31];case 3:return Mya[b&31]}return 0},C4=function(a){return a.o[a.Ic][a.l]},D4=function(a,b,c){2<=b&&1<a.l&&(--a.l,C4(a).ue=0);
var d=C4(a);d.timestamp=a.B.l+0;d.ue=Nya(b,c);32>a.l&&a.l++},Oya=function(a,b,c,d){for(var e=0;e<d;e++)for(var f=0;32>=f;f++)a.o[b+e][f].ln(a.o[c+e][f])},E4=function(a,b,c){for(var d=0;d<c;d++)for(var e=0;32>=e;e++)a.o[b+d][e].reset()},F4=function(a){a.Ic=0<a.g?a.g:1;
a.l=1;E4(a,0,15)},G4=function(a){this.A=a;
this.B=0;this.style=new x4;this.C=new A4(a);this.D=new A4(a);this.F=new A4(a);this.l=this.C;this.o=this.D;this.g=this.l},H4=function(a,b,c){var d=a.l,e=!1;
switch(a.style.get()){case 4:if(0<d.g)break;case 1:case 2:B4(d,c),F4(a.l),F4(a.o),d.Ic=15,d.g=b,e=!0}a.style.set(3);a.g=d;a.g.style=a.style;a.A.mode=1<<d.A;e?d.l=1:d.g!=b&&(d.g>b?(B4(d,c),E4(d,d.Ic-d.g,b)):d.Ic<b&&(b=d.g),d.g=b)},Pya=function(a){a.style.set(1);
a.g=a.o;a.g.g=0;a.g.style=a.style;a.A.mode=1<<a.g.A},Qya=function(a){a.style.set(4);
a.g=a.F;a.g.style=a.style;a.A.mode=1<<a.g.A},v4=function(a){this.l=a;
this.g=new y4;this.B=0;this.o=new G4(a);this.C=new G4(a);this.A=this.o},Gya=function(a,b,c,d){a.g.update();
b=Fya(b,c,a.g);switch(b.result){case 0:return;case 1:case 2:return}var e=b.Qm;c=b.Rm;if(32<=e||!e)a.l.mode&a.l.o&&(b=e,b&128&&(b=127),c&128&&(c=127),a=a.A.g,b&96&&D4(a,0,b),c&96&&D4(a,0,c),0!=b&&0!=c&&3==a.style.g&&B4(a,d));else if(e&16)a:if(!a.g.matches(e,c)&&(b=a.g,b.o=e,b.l=c,b.g=2,b=e&8?a.C:a.o,a.A=b,a.l.mode=1<<(a.B<<2)+(b.B<<1)+(4==b.style.g?1:0),(a.l.mode|1<<(a.B<<2)+(b.B<<1)+(4!=b.style.g?1:0))&a.l.o))if(c&64){d=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(e&7)<<1|c>>5&1];a=c&16?4*((c&14)>>1):
0;c=b.g;switch(b.style.get()){case 4:d=c.Ic;break;case 3:if(d!=c.Ic){if(d<c.g&&(d=c.g,d==c.Ic))break;var f=1+c.Ic-c.g,k=1+d-c.g;Oya(c,k,f,c.g);b=f;e=c.g;k<f?(f=k+e-f,0<f&&(b+=f,e-=f)):(f=f+e-k,0<f&&(e-=f));E4(c,b,e)}}c.Ic=d;c.l=a+1}else switch(e&7){case 1:switch(c&112){case 32:D4(b.g,0,32);break a;case 48:57==c?(b=b.g,C4(b).ue=0,32>b.l&&b.l++):D4(b.g,1,c&15)}break;case 2:c&32&&D4(b.g,2,c&31);break;case 3:c&32&&D4(b.g,3,c&31);break;case 4:case 5:if(32<=c&&47>=c)switch(c){case 32:Pya(b);break;case 33:b=
b.g;1<b.l&&(--b.l,C4(b).ue=0);break;case 36:b=b.g;d=C4(b);for(a=0;15>=a;a++)for(c=0;32>=c;c++)if(b.o[a][c]==d){for(;32>=c;c++)b.o[a][c].reset();break}break;case 37:H4(b,2,d);break;case 38:H4(b,3,d);break;case 39:H4(b,4,d);break;case 40:D4(b.g,0,32);break;case 41:b.style.set(2);b.g=b.l;b.g.g=0;b.g.style=b.style;b.A.mode=1<<b.g.A;break;case 42:d=b.F;d.g=15;d.style.set(4);F4(d);Qya(b);break;case 43:Qya(b);break;case 44:a=b.l;switch(b.style.get()){case 1:case 2:case 3:B4(a,d)}E4(a,0,15);break;case 45:b:{a=
b.g;switch(b.style.get()){default:case 2:case 1:break b;case 4:if(15>a.Ic){++a.Ic;a.l=1;break b}case 3:}2>a.g&&(a.g=2,a.Ic<a.g&&(a.Ic=a.g));b=a.Ic-a.g+1;B4(a,d);Oya(a,b,b+1,a.g-1);E4(a,a.Ic,1)}break;case 46:E4(b.o,0,15);break;case 47:B4(b.l,d);d=b.o;a=b.A.l+0;for(c=1;15>=c;++c)for(e=1;32>=e;++e)d.o[c][e].timestamp=a;d=b.o;b.o=b.l;b.l=d;Pya(b)}break;case 7:switch(c){case 33:case 34:case 35:b=b.g,32<(b.l+=c&3)&&(b.l=32)}}},I4=function(){},J4=function(a){this.o=a;
this.l=null},Sya=function(a,b,c){var d=a.getAttribute("t");
d=d?(0,window.parseInt)(d,10):1E3*(0,window.parseFloat)(a.getAttribute("start")||0);var e=a.getAttribute("d");e=e?(0,window.parseFloat)(e):1E3*(0,window.parseFloat)(a.getAttribute("dur")||0);b=a.getAttribute("w")||b;var f=!!a.getAttribute("append"),k=f?6:5;a=g.Xr("<html>"+(a.firstChild&&a.firstChild.nodeValue||"")+"</html>");Rya(d,e,k,b,f,a.firstChild,{},c)},Rya=function(a,b,c,d,e,f,k,l){switch(f.tagName){case "b":k.bold=!0;
break;case "i":k.As=!0;break;case "u":k.underline=!0;break;case "font":var m=f.getAttribute("color");K4.test(m);k.color=m}for(m=0;m<f.childNodes.length;m++){var n=f.childNodes[m];if(3==n.nodeType)l.push(new p4(a,b,c,d,n.nodeValue,e||0<m,g.Ub(k)?void 0:k));else{var q={};g.Ea(q,k);Rya(a,b,c,d,e||0<m,n,q,l)}}},L4=function(){this.o={};
this.l=null},M4=function(a){this.l={};
this.B={};this.C={};this.o="_"+r4++;this.A=a},N4=function(a,b){var c=a.getAttribute(b);
if(null!=c)return(0,window.parseFloat)(c)},O4=function(a,b){var c=a.getAttribute(b);
if(null!=c)return"1"==c},P4=function(a,b){var c=N4(a,b);
if(void 0!=c)return c},Q4=function(a,b){var c=a.getAttribute(b);
if(null!=c)return K4.test(c),c},Tya=function(a,b){var c={},d=b.getAttribute("ws");
g.Ea(c,d?a.C[d]:a.A);d=P4(b,"mh");null!=d&&(c.Ns=d);d=P4(b,"ju");null!=d&&(c.textAlign=d);d=P4(b,"pd");null!=d&&(c.dk=d);d=Q4(b,"wfc");null!=d&&(c.windowColor=d);d=N4(b,"wfo");void 0!=d&&(c.pk=d/255);return c},Uya=function(a,b){var c={},d=b.getAttribute("wp");
d&&g.Ea(c,a.B[d]);d=P4(b,"ap");null!=d&&(c.Wg=d);d=N4(b,"cc");null!=d&&(c.tH=d);d=N4(b,"ah");null!=d&&(c.ti=d);d=N4(b,"rc");null!=d&&(c.ip=d);d=N4(b,"av");null!=d&&(c.Oi=d);return c},Vya=function(a,b,c){var d={};
g.Ea(d,Uya(a,b));g.Ea(d,Tya(a,b));c?xya(d,a.A)?(c=a.o,d=a.A):c="_"+r4++:c=b.getAttribute("id")||"0";a=N4(b,"t");b=N4(b,"d")||0x8000000000000;return new q4(a,b,0,c,d)},R4=function(a,b,c){this.D=c;
this.version=this.B=this.C=this.g=0;this.l=new window.DataView(a);this.o=[]},S4=function(a){var b=a.g;
a.g+=1;return a.l.getUint8(b)},Wya=function(a){var b=a.g;
a.g+=4;return a.l.getUint32(b)},T4=function(a,b){this.o=a;
this.track="CC3"==b.C?4:0;this.l=new w4;this.l.o=1<<this.track},Yya=function(a){if(g.v(a))return!1;
a=new R4(a,8,0);return Xya(a)},Xya=function(a){if(!(a.g<a.l.byteLength)||1380139777!=Wya(a))return!1;
a.version=S4(a);if(1<a.version)return!1;S4(a);S4(a);S4(a);return!0},Zya=function(){this.l=[];
this.g=[]},U4=function(a,b){return b?a.g.concat(a.l):a.g},V4=function(a,b){switch(b.A){case "asr":var c=a.l;
g.Ia(c,(0,g.z)(b.I,b))||c.push(b);break;default:c=a.g,g.Ia(c,(0,g.z)(b.I,b))||c.push(b)}},W4=function(){this.l=null},$ya=function(a,b,c,d,e,f,k,l,m){switch(k.tagName){case "b":l.bold=!0;
break;case "i":l.As=!0;break;case "u":l.underline=!0}for(var n=0;n<k.childNodes.length;n++){var q=k.childNodes[n];if(3==q.nodeType)q=new p4(b,c,d,e.id,q.nodeValue,f||0<n,g.Ub(l)?void 0:l),m.push(q),e!=a.l&&e.l.push(q);else{var r={};g.Ea(r,l);$ya(a,b,c,d,e,!0,q,r,m)}}},X4=function(a){var b=0;
a=g.ma(a.split(":"));for(var c=a.next();!c.done;c=a.next())b=60*b+(0,window.parseFloat)(c.value);return 1E3*b},Y4=function(a){g.K.call(this);
this.Oy=!!a;this.l=new Zya;this.D=[];this.g=null},bza=function(a){var b={};
if(a=n4(a))b.lang=a,aza.test(a)&&(b.dk=1);return b},cza=function(a,b,c,d,e){d=d||0;
e=e||0;if(!g.v(b)){var f=new window.DataView(b);1718909296==f.getUint32(4)&&(f=g.zI(f,1835295092),b=b.slice(f.dataOffset,f.dataOffset+f.size),Yya(b)||(b=g.$d(new window.Uint8Array(b))))}if(g.v(b)){if("WEBVTT"==b.substring(0,6))return a.g||(a.g=new W4),a.g.g(b,d);b=g.Xr(b);if(!b||!b.firstChild)return[];a.g||("timedtext"==b.firstChild.tagName?3==(0,window.parseInt)(b.firstChild.getAttribute("format"),10)?a.g=new M4(bza(c)):a.g=new L4:a.g=new J4(bza(c)));return a.g.g(b,d)}try{if(Yya(b))return a.g||(a.g=
new T4(e,c)),a.g.g(b,d)}catch(k){g.GD(k)}return[]},Z4=function(a){Y4.call(this,a.Xm);
this.A=void 0;this.o=null;this.D=a.captionTranslationLanguages},$4=function(){this.ob=[]},a5=function(a,b,c,d,e,f){g.K.call(this);
this.I=a;this.A=b;this.C=new $4;this.g=null;this.F=d;this.L=f;this.l=this.o=null;this.K=c;this.D=e||!1;this.H=new g.Yt(this.ez,1E3,this);g.M(this,this.H);this.B=new g.zF(this);g.M(this,this.B);this.B.O(b,"seekto",this.jA);this.jA(b.getCurrentTime());this.ez()},dza=function(a,b){var c=a.g;
a.g=g.Ga(a.K.jh(b).Ca);c!=a.g&&a.L&&a.L()},eza=function(a,b){var c=g.eK(b,a.I,{}).Pa(),d={format:"RAW",
fd:(0,g.z)(a.zR,a),withCredentials:!0};a.D&&(d.responseType="arraybuffer");a.l=g.iE(c,d);a.o=b;c=a.C;d=a.o.Ca[0].ua;var e=g.cb(c.ob,d);0<=e||0>e&&1==(-e-1)%2||(e=-e-1,0<e&&1==d-c.ob[e-1]&&e<c.ob.length&&1==c.ob[e]-d?(g.Qa(c.ob,e),g.Qa(c.ob,e-1)):0<e&&1==d-c.ob[e-1]?c.ob[e-1]=d:e<c.ob.length&&1==c.ob[e]-d?c.ob[e]=d:(g.Ya(c.ob,e,0,d),g.Ya(c.ob,e+1,0,d)))},b5=function(a,b){Y4.call(this);
this.A=a;this.B=b;this.o=null;this.C=!1},fza=function(a,b){if(b in a.A.g)return a.A.g[b];
if(g.DK(a.A))for(var c in a.A.g){var d=a.A.g[c];if(g.bH(d.info.mimeType))return d}return null},gza=function(a,b){return a.za||g.X(b).Ua&&null!=a.pa&&null!=a.pa.g.rawcc},c5=function(a,b,c,d,e,f){t4.call(this,a,b,c,d,e,f);
this.type=1},d5=function(a,b,c,d,e,f){t4.call(this,a,b,c,d,e,f);
g.S(this.element,"ytp-caption-window-rollup");this.type=2;this.H=this.L=0;this.N=window.NaN;this.ka=null;this.X=new g.Yt(this.ER,433,this);g.M(this,this.X)},e5=function(a){if(!a.L){var b=g.xd("SPAN");
g.nh(b,u4(a,a.l.jb));a.A.appendChild(b);b.appendChild(g.yd("M"));var c=b.offsetHeight,d=g.xd("BR");b.appendChild(d);b.appendChild(g.yd("M"));a.L=b.offsetHeight-c;a.A.removeChild(b)}return a.L},f5=function(a,b,c,d){Y4.call(this,d);
c=c||g.SD(a).hl||"";c=c.split("_").join("-");this.B=g.UD(a,{hl:c});this.A=b;this.C={};this.o=null},i5=function(a){g.zV.call(this,a);
g.MG({YTP_CLICK_FOR_SETTINGS:"Click $GEAR_ICON for settings",YTP_SAMPLE_SUBTITLES:"Captions look like this"});this.o=g.X(a);this.A=a.ea();this.ka=g.$U(a);this.K=a;var b=null,c=g.cD("yt-html5-player-modules::subtitlesModuleData");c&&(b=new g.RC(c));this.ba=b;this.C={jb:{}};this.H={jb:{}};this.L=[];this.V={};this.Y={};this.N=!1;this.na="1"==this.A.oc.cc_auto_caps||"1"==this.o.gd.cc_auto_caps;this.F="3"==this.o.o&&!!a.app.B&&!!a.app.B.g.textTracks;c=b=this.l=this.B=this.D=this.I=this.X=this.fa=null;
this.F||(b=new g.Vt(this.BD,void 0,this),g.M(this,b),c=new g.Yt(this.oT,2E3,this),g.M(this,c));this.ca=b;this.da=c;this.W=new g.zF(this);g.M(this,this.W);this.F||this.W.O(a,"resize",this.Su);this.W.O(a,"onPlaybackAudioChange",this.DO);this.W.O(a,"crn_captions",this.eL,this);this.W.O(a,"crx_captions",this.fL,this);g5(this,h5(this,"display-settings")||{})},hza=function(a){if(a.A.captionTracks.length)var b=a.g.getAudioTrack().xw;
if("FORCED_ON"==b||1==a.o.ah||1==a.A.ah||"alwayson"==g.bO(a.A,"yt:cc"))return!0;if(2==a.o.ah){var c=h5(a,"module-enabled");if(null!=c)return!!c}return"ON"==b||"on"==g.bO(a.A,"yt:cc")},iza=function(a,b){if(a.B){var c=U4(a.B.l,b||a.na);
if(a.D&&a.D.g)return a.D.g;for(var d=[a.A.Zg,a.o.Zg,g.bO(a.A,"yt:cc_default_lang")],e=0;e<d.length;e++)for(var f=0;f<c.length;f++)if(n4(c[f])==d[e])return c[f];return a.D&&a.D.Sq?a.D.Sq:c[0]||a.D&&a.D.Fk}return null},jza=function(a,b){for(var c=a.K.app.B.g.textTracks,d=a.l.toString(),e=0;e<c.length;e++){var f=c[e];
f.id==d&&(b?"showing"!=f.mode&&(f.mode="showing"):"showing"==f.mode&&(f.mode="disabled"))}},j5=function(a,b,c,d){a.loaded&&a.unload();
null!=c&&(a.N=c);a.l=b;a.load(d)},kza=function(a,b){var c=g.B_(a.ka,!0).height;
if(!c)return null;var d=a.ka.Ra();switch(null!=b.params.Ns?b.params.Ns:b.params.cU?2:1<b.l.length?1:0){case 1:return new c5(b,a.C,a.H,c,d.width,d.height);case 2:return new d5(b,a.C,a.H,c,d.width,d.height);default:return new t4(b,a.C,a.H,c,d.width,d.height)}},g5=function(a,b,c){var d=k5.jb;
a.C={};g.Ea(a.C,k5);a.C.jb={};g.Ea(a.C.jb,d);a.H={jb:{}};var e=b.backgroundOverride?a.H:a.C,f=b.background||d.background;K4.test(f);e.jb.background=f;e=b.colorOverride?a.H:a.C;f=b.color||d.color;K4.test(f);e.jb.color=f;e=b.windowColorOverride?a.H:a.C;f=b.windowColor||k5.windowColor;K4.test(f);e.windowColor=f;e=b.backgroundOpacityOverride?a.H:a.C;f=b.backgroundOpacity;null==f&&(f=d.Ze);e.jb.Ze=f;e=b.fontSizeIncrementOverride?a.H:a.C;f=b.fontSizeIncrement;null==f&&(f=d.gj);e.jb.gj=f;e=b.textOpacityOverride?
a.H:a.C;f=b.textOpacity;null==f&&(f=d.Gh);e.jb.Gh=f;e=b.windowOpacityOverride?a.H:a.C;f=b.windowOpacity;null==f&&(f=k5.pk);e.pk=f;e=b.charEdgeStyleOverride?a.H:a.C;f=b.charEdgeStyle;null==f&&(f=d.Uh);e.jb.Uh=f;e=b.fontFamilyOverride?a.H:a.C;f=b.fontFamily;null==f&&(f=d.fontFamily);e.jb.fontFamily=f;a.loaded&&a.Su();c&&l5(a,"display-settings",b)},mza=function(a,b){if(b&&!a.I){var c=s4({dk:0,
lang:"en-GB"});a.I=[c,new p4(c.start,c.end-c.start,0,c.id,g.U("YTP_SAMPLE_SUBTITLES"))];g.mV(a.g,a.I)}else!b&&a.I&&(lza(a,a.I),a.I=null)},lza=function(a,b){g.oV(a.g,b);
(0,g.C)(b,function(a){g.Ra(this.L,a)},a);
a.ca.Nk()},nza=function(a,b){return a&&g.v(a)&&K4.test(a)?a:b},oza=function(a,b){return g.ta(a)&&!(0,window.isNaN)(a)?Math.max(0,Math.min(1,(0,window.parseFloat)(a))):b},qza=function(a,b){if(a&&g.v(a)){var c=pza.indexOf(a);
return-1!=c?c:b}return b},sza=function(a,b){if(a&&g.v(a)){var c=rza.indexOf(a);
return-1!=c?c:b}return b},tza=function(a,b){return g.ta(a)&&!(0,window.isNaN)(a)?g.Xc(a,-2,4):b},h5=function(a,b){if(!a.ba)return null;
try{var c=a.ba.get(b)}catch(d){a.ba.remove(b)}return c},l5=function(a,b,c){if(a.ba)try{a.ba.set(b,c)}catch(d){}};
g.jI.prototype.Mn=g.ca(4,function(a){return(a=this.bi(a))?a.l:0});
g.tK.prototype.Mn=g.ca(3,function(){return 0});
g.dI.prototype.I=g.ca(2,function(a){return a?this.toString()==a.toString():!1});
var aza=/^(ar|ckb|dv|he|iw|fa|nqo|ps|sd|ug|ur|yi|.*[-_](Arab|Hebr|Thaa|Nkoo|Tfng))(?!.*[-_](Latn|Cyrl)($|-|_))($|-|_)/i,zya=/#(.)(.)(.)/,yya=/^#(?:[0-9a-f]{3}){1,2}$/i,K4=/^#(?:[0-9a-f]{3}){1,2}$/i,rza="default monoSerif propSerif monoSans propSans casual cursive smallCaps".split(" "),pza=["none","raised","depressed","uniform","dropShadow"];var Bya=["left","right","center"];var k5={windowColor:"#080808",pk:0,textAlign:2,Wg:7,ti:50,Oi:100,jb:{background:"#080808",Ze:.75,Uh:0,color:"#fff",fontFamily:4,gj:0,Gh:1,offset:1}};g.p(p4,g.dQ);g.p(q4,g.dQ);var r4=0;g.p(t4,g.V);g.h=t4.prototype;g.h.UM=function(a,b){var c=g.Fh(this.element,this.element.parentElement);this.ba=a-c.x;this.ca=b-c.y;g.S(this.element,"ytp-dragging")};
g.h.TM=function(a,b){var c=g.Ih(this.element),d=a-this.ba-.02*this.ra,e=b-this.ca-.02*this.oa,f=(d+c.width/2)/this.W*3;f=Math.floor(g.Xc(f,0,2));var k=(e+c.height/2)/this.da*3;k=Math.floor(g.Xc(k,0,2));var l=f+3*k;d=(d+f/2*c.width)/this.W;d=100*g.Xc(d,0,1);c=(e+k/2*c.height)/this.da;c=100*g.Xc(c,0,1);this.D.params.Wg=l;this.D.params.Oi=c;this.D.params.ti=d;this.l.Wg=l;this.l.Oi=c;this.l.ti=d;this.uC()};
g.h.SM=function(){g.vq(this.element,"ytp-dragging")};
g.h.uC=function(){this.Li(this.o)};
g.h.Vb=function(){return this.type};
g.h.Li=function(a){var b=Math.min(this.Mx(),this.W),c=this.Lx();g.nh(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"96%","max-height":"96%",margin:"",transform:""});this.rq(a);a={transform:"",top:"",left:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"","max-height":""};var d=.96*this.l.ti+2,e=this.l.Wg;switch(e){case 0:case 3:case 6:a.left=d+"%";break;case 1:case 4:case 7:a.left=d+"%";d=this.A.offsetWidth;b||d?(b=b||d+1,a.width=b+"px",a["margin-left"]=
b/-2+"px"):a.transform+=" translateX(-50%)";break;case 2:case 5:case 8:a.right=100-d+"%"}b=.96*this.l.Oi+2;switch(e){case 0:case 1:case 2:a.top=b+"%";break;case 3:case 4:case 5:a.top=b+"%";(c=c||this.element.clientHeight)?(a.height=c+"px",a["margin-top"]=c/-2+"px"):a.transform+=" translateY(-50%)";break;case 6:case 7:case 8:a.bottom=100-b+"%"}g.nh(this.element,a)};
g.h.rq=function(a){var b;for(b=0;b<a.length&&a[b]==this.o[b];b++);if(this.I||this.o.length>b)b=0,this.I=!1,this.o=[],this.C=[],this.F=[],this.B=null,g.Bd(this.A);for(;b<a.length;b++)Cya(this,a[b])};
g.h.Mx=function(){return 0};
g.h.Lx=function(){return 0};Dya.prototype.A=function(){};w4.prototype.clear=function(){this.A=this.l=this.mode=0;this.g=[];this.reset()};
w4.prototype.reset=function(){this.mode=0;this.B.reset(0);this.C.reset(1)};
var Eya=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];x4.prototype.set=function(a){this.g=a};
x4.prototype.get=function(){return this.g};
y4.prototype.clear=function(){this.g=0};
y4.prototype.update=function(){this.g=2==this.g?1:0};
y4.prototype.matches=function(a,b){return 0!=this.g&&a==this.o&&b==this.l};
z4.prototype.ln=function(a){this.ue=a.ue;this.timestamp=a.timestamp};
z4.prototype.reset=function(){this.timestamp=this.ue=0};
A4.prototype.debugString=function(){for(var a="\n",b=1;15>=b;++b){for(var c=1;32>=c;++c){var d=this.o[b][c];a=0==d.ue?a+"_":a+String.fromCharCode(d.ue)}a+="\n"}return a};
A4.prototype.reset=function(a){for(var b=0;15>=b;b++)for(var c=0;32>=c;c++)this.o[b][c].reset();this.A=a;this.g=0;this.l=this.Ic=1};
var Jya=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],Kya=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],Lya=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],Mya=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];G4.prototype.reset=function(a,b){this.B=b;this.style.set(2);this.l=this.C;this.o=this.D;this.g=this.l;var c=(a<<2)+(b<<1);this.C.reset(c);this.D.reset(c);this.F.reset((a<<2)+(b<<1)+1)};
v4.prototype.reset=function(a){this.B=a;this.g.clear();this.A=this.o;this.o.reset(a,0);this.C.reset(a,1)};I4.prototype.reset=function(){};g.p(J4,I4);J4.prototype.g=function(a){var b=[];this.l||(this.l=s4(this.o),b.push(this.l));a=g.ma(a.firstChild.childNodes);for(var c=a.next();!c.done;c=a.next())Sya(c.value,this.l.id,b);return b};g.p(L4,I4);
L4.prototype.g=function(a){var b=[];this.l||(this.l=s4(),this.o[this.l.id]=this.l,b.push(this.l));for(a=a.firstChild.firstChild;a;){switch(a.tagName){case "window":var c=a,d=c.getAttribute("id");a:{var e=c,f=this.o[d];if(e.getAttribute("t")||e.getAttribute("start")){c=e.getAttribute("start")?1E3*(0,window.parseFloat)(e.getAttribute("start")):(0,window.parseInt)(e.getAttribute("t"),10);f&&(f.end>=c?f.end=c:f=null);switch(e.getAttribute("op")){case "kill":c=null;break a;case "define":f=null}f||(f=s4());
var k={};f&&(g.Ea(k,f.params),f=f.params.jb)&&(k.jb={},g.Ea(k.jb,f));e.getAttribute("rc")&&(k.ip=(0,window.parseInt)(e.getAttribute("rc"),10));e.getAttribute("cc")&&(k.tH=(0,window.parseInt)(e.getAttribute("cc"),10));e.getAttribute("ap")&&(f=(0,window.parseInt)(e.getAttribute("ap"),10),k.Wg=0>f||8<f?7:f);e.getAttribute("ah")&&(k.ti=(0,window.parseInt)(e.getAttribute("ah"),10));e.getAttribute("av")&&(k.Oi=(0,window.parseInt)(e.getAttribute("av"),10));e.getAttribute("vs")&&(k.isVisible=!!e.getAttribute("vs"));
e.getAttribute("ju")&&(k.textAlign=(0,window.parseInt)(e.getAttribute("ju"),10));e.getAttribute("pd")&&(k.dk=1,0==(0,window.parseInt)(e.getAttribute("pd"),10)&&(k.dk=0));e.getAttribute("bc")&&(k.jb||(k.jb={}),k.jb.backgroundColor=e.getAttribute("bc"));e.getAttribute("bo")&&(k.jb||(k.jb={}),k.jb.Ze=(0,window.parseInt)(e.getAttribute("bo"),10)/100);e.getAttribute("fc")&&(k.jb||(k.jb={}),k.jb.color=e.getAttribute("fc"));e.getAttribute("sd")&&(k.cU=(0,window.parseInt)(e.getAttribute("sd"),10));f=(0,window.parseInt)(e.getAttribute("d"),
10)||1E3*(0,window.parseFloat)(e.getAttribute("dur"))||0x8000000000000;e=e.getAttribute("id")||"0";c=new q4(c,f,0,e,k)}else c=null}this.o[d]=c;b.push(c);break;case "text":for(d=[],Sya(a,this.l.id,d),d=g.ma(d),c=d.next();!c.done;c=d.next())c=c.value,this.o[c.windowId]&&b.push(c)}a=a.nextSibling}return b};g.p(M4,I4);
M4.prototype.g=function(a){a.firstChild.getAttribute("format");a=g.ma(a.firstChild.childNodes);for(var b=a.next();!b.done;b=a.next())if(b=b.value,1==b.nodeType)switch(b.tagName){case "head":var c=b;break;case "body":var d=b}if(c)for(c=g.ma(c.childNodes),a=c.next();!a.done;a=c.next())if(a=a.value,1==a.nodeType)switch(a.tagName){case "pen":b=a.getAttribute("id");var e=this.l,f={},k=a.getAttribute("p");k&&g.Ea(f,this.l[k]);k=O4(a,"b");null!=k&&(f.bold=k);k=O4(a,"i");null!=k&&(f.As=k);k=O4(a,"u");null!=
k&&(f.underline=k);k=P4(a,"et");null!=k&&(f.Uh=k);k=P4(a,"of");null!=k&&(f.offset=k);k=Q4(a,"bc");null!=k&&(f.background=k);k=Q4(a,"ec");null!=k&&(f.Fw=k);k=Q4(a,"fc");null!=k&&(f.color=k);k=P4(a,"fs");void 0!=k&&0!=k&&(f.fontFamily=k);k=N4(a,"sz");void 0!=k&&(f.gj=k/100-1);k=N4(a,"bo");void 0!=k&&(f.Ze=k/255);a=N4(a,"fo");void 0!=a&&(f.Gh=a/255);e[b]=f;break;case "ws":b=a.getAttribute("id");this.C[b]=Tya(this,a);break;case "wp":b=a.getAttribute("id"),this.B[b]=Uya(this,a)}c=[];if(d)for(a={},b=void 0,
d=g.ma(d.childNodes),e=d.next();!e.done;e=d.next())if(e=e.value,1==e.nodeType)switch(e.tagName){case "w":var l=Vya(this,e,!1);(e=a[l.id])&&e.end>l.start&&(e.end=l.start);a[l.id]=l;c.push(l);break;case "p":var m=b,n=Pc;f=[];k=e.getAttribute("w")||this.o;var q=!!O4(e,"a"),r=N4(e,"t")||0,u=N4(e,"d")||5E3;!n&&!q&&m&&m.windowId==k&&m.end>r&&(m.end=r);m=q?6:5;n=this.l[e.getAttribute("p")];for(var B=e.childNodes,E=0;E<B.length;E++){var L=B[E];0<E&&(q=!0);var Y=void 0;1==L.nodeType&&(Y=L);if(Y&&"s"==Y.tagName){var ka=
Y;L=r;Y=u;var ab=k,R=q,$b=m,se=ka.textContent?ka.textContent:"",sb=this.l[ka.getAttribute("p")];ka=N4(ka,"t")||0;L=new p4(L+ka,Y-ka,$b,ab,se,R,sb)}else L=new p4(r,u,m,k,L.textContent||"",q,n);f.push(L)}b&&"\n"==b.text&&(b.text="");if(0<f.length){b=f[f.length-1];var Pc=null!=e.getAttribute("d");f[0].windowId==this.o&&(l=Vya(this,e,!0),c.push(l));e=g.ma(f);for(f=e.next();!f.done;f=e.next())f=f.value,f.windowId=l.id,l.l.push(f),c.push(f)}}return c};g.p(R4,Dya);R4.prototype.A=function(a,b,c,d,e){if(c<d){var f="_"+r4++;c=c/1E3-this.D;d=d/1E3-this.D;a=new q4(c,d-c,5,f,{textAlign:0,Wg:0,ti:2.5*b,Oi:5.33*a});e=new p4(c,d-c,5,f,e);this.o.push(a);this.o.push(e)}};
g.p(T4,I4);T4.prototype.g=function(a){a=new R4(a,a.byteLength,this.o);if(Xya(a)){for(;a.g<a.l.byteLength;)for(0==a.version&&(a.C=Wya(a)*(1E3/45)),a.B=S4(a);0<a.B;a.B--){var b=S4(a),c=S4(a),d=S4(a);b&4&&(b&3)==this.track&&(0==this.track||1==this.track)&&(b=this.l,b.g.push({time:a.C,type:this.track,Aw:c,Bw:d,order:b.g.length}))}Iya(this.l,a);return a.o}return[]};
T4.prototype.reset=function(){this.l.clear()};g.p(W4,I4);
W4.prototype.g=function(a,b){for(var c=[],d=a.split(uza),e=1;e<d.length;e++){var f=d[e],k=b;if(""!=f&&!vza.test(f)){var l=m5.exec(f);if(l&&3<=l.length){var m=X4(l[1]);l=X4(l[2])-m;m+=k;f=f.substring(m5.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");m5.lastIndex=0;var n=f;f={};this.l||(this.l=s4({Ns:0}),c.push(this.l));var q=this.l;k=5;if(0>n.indexOf("<")&&0>n.indexOf("&"))c.push(new p4(m,l,k,q.id,n,!1,g.Ub(f)?void 0:f));else{n=n.split(wza);1!=n.length&&(k=6,q="_"+xza++,q=new q4(m,l,k,q,{}),c.push(q));
for(var r=m,u=0;u<n.length;u++){var B=n[u];if(0==u%2){var E=g.Xr("<html>"+B+"</html>");if(E.getElementsByTagName("parsererror").length){var L=E.createElement("span");L.appendChild(E.createTextNode(B))}else L=E.firstChild;$ya(this,r,l-(r-m),k,q,0<u,L,f,c)}else r=X4(B)}}}m5.lastIndex=0}}return c};
var xza=0,vza=/^NOTE/,uza=/(?:\r\n|\r|\n){2,}/,m5=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3}).*(?:\r\n|\r|\n)","gm"),wza=/<((?:[\d]{2}:)?[\d]{2}:[\d]{2}\.[\d]{3})>/;g.p(Y4,g.K);Y4.prototype.trackCount=function(){return U4(this.l,!0).length};
Y4.prototype.Id=function(){this.g=null};
Y4.prototype.U=function(){g.K.prototype.U.call(this);this.Id()};
Y4.prototype.gC=function(){return!1};g.p(Z4,Y4);g.h=Z4.prototype;g.h.Hs=function(a,b){var c=this.Lk(a),d=(0,g.z)(function(c){this.o=null;b(c.responseText,a)},this);
this.Id();this.o=g.iE(c,{format:"RAW",Hb:d,withCredentials:!0})};
g.h.Is=function(a,b,c,d){this.A=c;if(d)for(b=g.ma(d.captionTracks),c=b.next();!c.done;c=b.next())V4(this.l,c.value);a()};
g.h.Lk=function(a){var b=a.Pa(),c={};if(this.A||a.o)c.fmt=this.A||"srv"+a.o;a.g&&(c.tlang=a.g.languageCode);return g.UD(b,c)};
g.h.Id=function(){Y4.prototype.Id.call(this);this.o&&this.o.abort()};
g.h.U=function(){this.Id();Y4.prototype.U.call(this)};$4.prototype.contains=function(a){a=g.cb(this.ob,a);return 0<=a||0>a&&1==(-a-1)%2};
$4.prototype.length=function(){return this.ob.length/2};g.p(a5,g.K);g.h=a5.prototype;g.h.U=function(){g.K.prototype.U.call(this);this.l&&this.l.abort()};
g.h.jA=function(a){var b=this;if(this.K.wc())var c=this.B.O(this.A,"progresssync",function(){b.reset();b.g=null;dza(b,b.A.getCurrentTime());b.B.Ba(c)});
else dza(this,a)};
g.h.reset=function(){this.C=new $4;this.l&&(this.l.abort(),this.l=null)};
g.h.ez=function(){var a;if(a=null!==this.g)a=this.g,a=a.g.yi(a);!a||this.l||this.g&&30<this.g.startTime-this.A.getCurrentTime()||(a=this.g,a=a.g.jl(a),!g.X(this.A).experiments.g("disable_captions_unknown_requests")&&!a.Ca[0].duration)||(this.C.contains(a.Ca[0].ua)||eza(this,a),this.g=g.Ga(a.Ca));this.H.start()};
g.h.zR=function(a){var b=!(this.D?a.response:a.responseText)||400<=a.status;if(!g.X(this.A).experiments.g("disable_captions_redirects_redux")){var c=g.yK(a);if(c){a=g.eK(this.o,this.I,{});b=this.o;g.aK(b.g,a,c);b.requestId=a.get("req_id");eza(this,this.o);return}}b||null===this.F||(this.D?this.F(a.response,1E3*this.o.Ca[0].startTime):this.F(a.responseText,1E3*this.o.Ca[0].startTime));this.l=this.o=null};g.p(b5,Y4);g.h=b5.prototype;g.h.Hs=function(a,b){this.Id();var c=fza(this,a.l);if(c){var d=c.index.Mn(c.index.Ff());g.X(this.B).experiments.g("html5_disable_caption_starttime")||(d-=c.index.Xd(c.index.Ff()));d*=1E3;var e=g.X(this.B).Ua;this.o=new a5(new g.KJ,this.B,c,function(c,e){b(c,a,e,d)},e||g.ZG(c.info),(0,g.z)(function(){e&&(this.o&&this.o.reset(),this.g&&this.g.reset(),this.C=!0)},this))}};
g.h.gC=function(){var a=this.C;this.C=!1;return a};
g.h.Is=function(a){g.X(this.B).Ua?(V4(this.l,new g.dI({format:1,languageCode:"rawcc",languageName:"CC1",name:"",is_servable:!0,is_default:!0,is_translateable:!1})),V4(this.l,new g.dI({format:1,languageCode:"rawcc",languageName:"CC3",name:"",is_servable:!0,is_default:!0,is_translateable:!1}))):V4(this.l,new g.dI({format:1,languageCode:"en",languageName:"English",name:"",is_servable:!0,is_default:!0,is_translateable:!1}));a()};
g.h.Id=function(){Y4.prototype.Id.call(this);this.o&&(this.o.dispose(),this.o=null)};
g.h.Lk=function(){return""};
g.h.U=function(){this.Id();Y4.prototype.U.call(this)};g.p(c5,t4);c5.prototype.rq=function(a){var b=this.D.l;t4.prototype.rq.call(this,a);for(a=a.length;a<b.length;a++){var c=b[a];if(f&&c.l==e)var d=f;else{d={};g.Ea(d,c.l);g.Ea(d,yza);var e=c.l;var f=d}Cya(this,c,d)}};
var yza={Jr:!0};g.p(d5,t4);g.h=d5.prototype;g.h.uC=function(){g.$t(this.X)};
g.h.ER=function(){g.vq(this.element,"ytp-rollup-mode");this.Li(this.ka,!0)};
g.h.Mx=function(){return this.H};
g.h.Lx=function(){return this.D.params.ip*e5(this)};
g.h.Li=function(a,b){this.ka=a;if(e5(this)){for(var c=0,d=0;d<this.o.length&&c<a.length;d++)this.o[d]==a[c]&&c++;0<c&&c<a.length&&(a=this.o.concat(a.slice(c)));c=this.H;this.H=0;t4.prototype.Li.call(this,a);this.H=Math.max(c,this.A.offsetWidth+1);c=this.D.params.ip*e5(this)-this.A.offsetHeight;c!=this.N&&(b||(0,window.isNaN)(this.N)||(g.S(this.element,"ytp-rollup-mode"),g.Zt(this.X)),g.nh(this.A,"transform",c?"translateY("+c+"px)":""),this.N=c);t4.prototype.Li.call(this,a)}else t4.prototype.Li.call(this,
a)};g.p(f5,Y4);g.h=f5.prototype;g.h.Hs=function(a,b){var c=this.Lk(a),d=(0,g.z)(function(c){this.o=null;b(c.responseText,a)},this);
this.Id();this.o=g.iE(c,{format:"RAW",Hb:d,withCredentials:!0})};
g.h.Is=function(a,b,c){var d=this.B;b={type:"list",tlangs:1,v:this.A,fmts:Number(b||!1),vssids:1};this.Oy&&(b.asrs=1);d=g.UD(d,b);b=(0,g.z)(function(b){this.o=null;if((b=b.responseXML)&&b.firstChild){for(var d=this.l,e=g.ma(b.getElementsByTagName("track")),l=e.next();!l.done;l=e.next()){var m=l.value;l=m.getAttribute("formats");var n=m.getAttribute("lang_code"),q=m.getAttribute("lang_translated"),r=m.getAttribute("name"),u=m.getAttribute("kind"),B=m.getAttribute("id"),E="true"==m.getAttribute("cantran");
m=m.getAttribute("vss_id");V4(d,new g.dI({formats:l,format:c,languageCode:n,languageName:q,name:r,kind:u,id:B,is_servable:!0,is_translateable:E,vss_id:m}))}b=b.getElementsByTagName("target");d=b.length;for(e=0;e<d;e++)l=b[e].getAttribute("lang_code"),n=b[e].getAttribute("lang_translated"),q=b[e].getAttribute("lang_original"),r=b[e].getAttribute("id"),l={languageCode:l,languageName:n,languageOriginal:q,id:r},this.C[l.languageCode]=l.languageName,this.D.push(new g.cI(l))}a()},this);
this.Id();this.o=g.iE(d,{format:"RAW",Hb:b,withCredentials:!0})};
g.h.Lk=function(a){var b=this.B,c={v:this.A,type:"track",lang:a.l,name:a.B,kind:a.A,fmt:a.o};a.g&&(c.tlang=n4(a));return b=g.UD(b,c)};
g.h.Id=function(){Y4.prototype.Id.call(this);this.o&&this.o.abort()};
g.h.U=function(){this.Id();Y4.prototype.U.call(this)};g.p(i5,g.zV);g.h=i5.prototype;g.h.U=function(){if(this.F){var a=this.K.app.B;a&&wya(a)}else mza(this,!1);g.zV.prototype.U.call(this)};
g.h.Hz=function(){return this.F?!this.A.za:this.A.captionTracks.length&&this.g.getAudioTrack().Fk?!0:hza(this)};
g.h.load=function(a){g.zV.prototype.load.call(this);this.D=this.g.getAudioTrack();if(this.B||a)this.l?(this.F&&!this.o.experiments.g("disable_native_caption_api")?jza(this,!0):a?this.PB(a,this.l):3!=this.g.Ta()&&this.B.Hs(this.l,(0,g.z)(this.PB,this)),this.g.sa("captionschanged",m4(this.l))):this.g.sa("onCaptionsTrackListChanged");else{var b;gza(this.A,this.K)?b=new b5(this.A.pa,this.g):this.A.captionTracks.length?b=new Z4(this.A):b=new f5(this.A.Ym,this.A.videoId,this.A.Zg||this.o.Zg||g.bO(this.A,
"yt:cc_default_lang")||this.o.Na,this.A.Xm);this.B=b;b.Is((0,g.z)(this.fS,this),!0,this.F?"vtt":void 0,this.g.getAudioTrack())}};
g.h.unload=function(){this.F?this.o.experiments.g("disable_native_caption_api")?wya(this.K.app.B):this.l&&jza(this,!1):(this.da&&g.au(this.da),g.pV(this.g,"captions"),this.L=[],this.B&&this.B.Id(),this.I&&g.mV(this.g,this.I),this.Su());g.zV.prototype.unload.call(this);var a=g.YU(this.g.app);a&&a.C&&g.eP(a.C.o);this.g.sa("captionschanged",{})};
g.h.fS=function(){if(this.N||hza(this))var a=iza(this,this.N);if(this.F){for(var b=U4(this.B.l,!0),c=[],d=0;d<b.length;d++){var e=b[d],f={kind:"subtitles",label:g.eI(e),srclang:n4(e),src:this.B.Lk(e),id:e.toString()};e==a&&(f["default"]=1);c.push(g.J("TRACK",f))}a=this.K.app.B;for(b=0;b<c.length;b++)a.g.appendChild(c[b]);(c=this.K.app.B.g)&&c.textTracks&&c.textTracks.addEventListener&&!this.o.experiments.g("disable_native_caption_api")&&this.W.O(c.textTracks,"change",this.gS)}else!this.l&&a&&j5(this,
a),this.g.sa("onCaptionsTrackListChanged"),this.g.sa("onApiChange")};
g.h.gS=function(){for(var a=this.K.app.B.g.textTracks,b=null,c=0;c<a.length;c++)if("showing"==a[c].mode)a:{b=U4(this.B.l,!0);for(var d=0;d<b.length;d++)if(b[d].toString()==a[c].id){b=b[d];break a}b=null}(this.loaded?this.l:null)!=b&&j5(this,b,!0)};
g.h.mU=function(){this.o.experiments.g("disable_native_caption_api")?this.loaded&&!this.F&&this.unload():!this.l&&this.F||this.unload()};
g.h.PB=function(a,b,c,d){if(a){this.B.gC()&&(this.L=[],g.pV(this.K,"captions"),this.ca.Nk());a=cza(this.B,a,b,c,d);g.mV(this.g,a);if(this.N&&(a={trackName:b.B,trackKind:b.A,trackLangCode:n4(b)},b.g&&(a.fromLangCode=b.l),g.gV(this.g,"cc",a),this.l!=(this.D&&this.D.Fk))){!this.N||g.cM(this.o)||g.tM(this.o)||(g.au(this.da),b=s4({Wg:0,ti:5,Oi:5,ip:2,textAlign:0,dk:0,lang:"en-GB"}),this.X=[b],a=g.U("YTP_CLICK_FOR_SETTINGS").split("$GEAR_ICON"),this.fa||(c=new g.IH(g.doa()),g.M(this,c),this.fa=c.element),
c=b.end-b.start,(d=g.eI(this.l))&&this.X.push(new p4(b.start,c,0,b.id,d)),this.X.push(new p4(b.start,c,0,b.id,a[0]),new p4(b.start,c,0,b.id,this.fa,!0),new p4(b.start,c,0,b.id,a[1],!0)),g.mV(this.g,this.X),g.Zt(this.da));if(this.N||g.cM(this.o))l5(this,"module-enabled",!0),this.D&&(this.D.g=this.l);(b=g.YU(this.g.app))&&b.C&&g.eP(b.C.o)}this.N=!1}};
g.h.eL=function(a){this.L.push(a);this.ca.Nk()};
g.h.fL=function(a){g.Ra(this.L,a);var b=gza(this.A,this.K)&&this.o.Ua;!this.o.experiments.g("disable_remove_displayed_close_caption_cue")&&b&&g.oV(this.g,[a]);this.ca.Nk()};
g.h.aT=function(a){if(a instanceof q4){var b=this.V[a.id];b&&b.D!=a&&(b.dispose(),delete this.V[a.id],b=null);b||(b=kza(this,a))&&(this.V[a.id]=b)}else b=a.windowId,this.Y[b]||(this.Y[b]=[]),this.Y[b].push(a)};
g.h.oT=function(){lza(this,this.X);this.X=null};
g.h.BD=function(){this.ca.stop();g.Vb(this.Y);this.L.sort(g.fQ);var a=this.L;if(this.I){var b=(0,g.Fd)(a,function(a){return-1==this.I.indexOf(a)},this);
b.length&&(a=b)}(0,g.C)(a,this.aT,this);g.Ib(this.V,function(a,b){this.Y[b]?(a.element.parentNode||g.tV(this.g,a.element,4),a.Li(this.Y[b])):(a.dispose(),delete this.V[b])},this)};
g.h.tC=function(){g5(this,{},!0)};
g.h.lr=function(){var a=k5.jb;a={background:a.background,backgroundOpacity:a.Ze,charEdgeStyle:a.Uh,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.gj,textOpacity:a.Gh,windowColor:k5.windowColor,windowOpacity:k5.pk};var b=h5(this,"display-settings"),c;for(c in b)null!=b[c]&&(a[c]=b[c]);return a};
g.h.Uu=function(a,b){var c={};g.Ea(c,h5(this,"display-settings"));g.Ea(c,a);g5(this,c,b);this.g.P("captionssettingschanged")};
g.h.Su=function(){!this.F&&this.loaded&&(g.Ib(this.V,function(a,b){a.dispose();delete this.V[b]},this),this.BD())};
g.h.Vs=function(a,b){switch(a){case "fontSize":if((0,window.isNaN)(b))break;var c=g.Xc(b,-2,4);this.Uu({fontSizeIncrement:c});return c;case "reload":b&&!this.F&&j5(this,this.l,!0);break;case "stickyLoading":void 0!=b&&this.o.wb&&l5(this,"module-enabled",!!b);break;case "track":if(!this.B)return{};if(b){if(this.F)break;if(!g.Aa(b))break;if(g.Ub(b)){j5(this,null,!0);break}for(var d=U4(this.B.l,!0),e=0;e<d.length;e++){var f=d[e];f.l!=b.languageCode||c&&f.C!=b.languageName||(c=b.translationLanguage?vya(f,
b.translationLanguage):f)}!c||c==this.l&&this.loaded||j5(this,c,!0)}else return this.loaded&&this.l&&this.l!=(this.D&&this.D.Fk)?m4(this.l):{};return"";case "tracklist":return this.B?(0,g.H)(U4(this.B.l,!(!b||!b.includeAsr)),function(a){return m4(a)}):[];
case "translationLanguages":return this.B?this.B.D:[];case "displaySettings":c=this.lr();if(g.cM(this.o)&&b&&g.Aa(b))if(b.reset)this.tC();else{f={};for(d in b)switch(d){case "color":case "background":case "windowColor":f[d]=nza(b[d],c[d]);break;case "textOpacity":case "backgroundOpacity":case "windowOpacity":f[d]=oza(b[d],c[d]);break;case "charEdgeStyle":f[d]=qza(b[d],c[d]);break;case "fontSizeIncrement":f[d]=tza(b[d],c[d]);break;case "fontFamilyOption":f.fontFamily=sza(b[d],c[d])}for(e in f)f[e+
"Override"]=!0;this.Uu(f,!0);c=this.lr()}c.fontFamilyOption=rza[c.fontFamily];c.charEdgeStyle=pza[c.charEdgeStyle];return c;case "sampleSubtitles":this.F||void 0==b||mza(this,!!b);break;case "xmlTrack":b&&this.o.wb&&(this.F||j5(this,new g.dI({languageName:b.name}),!1,b.xml))}};
g.h.cL=function(){var a="reload fontSize track tracklist translationLanguages displaySettings sampleSubtitle".split(" ");this.o.wb&&a.push("stickyLoading","xmlTrack");return a};
g.h.dL=function(){var a=this.l;return a?{cc:a.D}:{}};
g.h.lD=function(){this.loaded&&this.l?(l5(this,"module-enabled",!1),this.unload()):j5(this,this.l||iza(this,!0),!0)};
g.h.DO=function(){this.A.captionTracks.length&&(this.loaded&&this.unload(),this.Hz()&&this.load())};g.fY.captions=i5;})(_yt_player);
