; Class for position class objects
; It keeps record of all characterstics of position like what is present at what position
(define pos%
  (class object%
    (define bomberman #f) 
    (define enemy #f)
    (define perm-wall #f)
    (define brick-wall #f)
    (define door #f)
    (define power #f)
    (define bomb #f)
    (define flame #f)
    (define image "Images/bg-block.jpg")
    (super-new)
    (define/public (is-any-thing?)
      (or enemy perm-wall brick-wall bomb))
    (define/public (is-bomberman?) bomberman)
    (define/public (is-enemy?) enemy)
    (define/public (is-perm-wall?) perm-wall) 
    (define/public (is-brick-wall?) brick-wall)
    (define/public (is-door?) door)
    (define/public (is-power?) power)
    (define/public (is-bomb?) bomb)
    (define/public (is-flame?) flame)
    (define/public (get-image) image)
    (define/public (initialise b e pw bw d p bom f)
      (set! bomberman b)
      (set! enemy e)
      (set! perm-wall pw)
      (set! brick-wall bw)
      (set! door d)
      (set! power p)
      (set! bomb bom)
      (set! flame f))
    (define/public (set-bomberman x)
      (set! bomberman x))
    (define/public (set-enemy x)
      (set! enemy x))
    (define/public (set-perm-wall x)
      (set! perm-wall x))
    (define/public (set-brick-wall x)
      (set! brick-wall x))
    (define/public (set-door x)
      (set! door x))
    (define/public (set-power x)
      (set! power x))
    (define/public (set-bomb x)
      (set! bomb x))
    (define/public (set-image im)
      (set! image im))
    (define/public (set-flame x)
      (set! flame x))))    